name: publish
on:
  push:
  workflow_dispatch:
env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_BUILD_NUMBER: ${{github.run_number}}
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - run: git tag ${{github.run_number}}
      - name: Execute Gradle build
        run: ./gradlew publish
      - run: |
          mkdir _work
          cd _work
          git clone --branch publish --single-branch https://${{ secrets.GITHUB_TOKEN }}:${{github.actor}}@github.com/${{ github.repository }} Minestom
          cd Minestom
          mkdir libraries
          echo "com.github.Minestom:minestom:${{github.run_number}}
          https://$_ACTOR:$_TOKEN@maven.pkg.github.com/FreedyPlugins/Minestom" > ./libraries/release
          git add .
          git commit -m "Release ${{github.run_number}}"
          git push origin publish